name: RetiroQuest
options:
  bundleIdPrefix: br.com.rafael
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
targets:
  RetiroQuest:
    type: application
    platform: iOS
    sources:
      - RetiroQuest
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: br.com.rafael.RetiroQuest
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: Retiro Quest
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationPortrait
        SWIFT_VERSION: "5.0"
        TARGETED_DEVICE_FAMILY: "1"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: "1.0"
